xkb: Fix bounds checking in XkmGetCountedString()
As reported by the static analyzer:

Error: GCC_ANALYZER_WARNING (CWE-823): [#def119]
| xkb/xkmread.c: scope_hint: In function ‘XkmGetCountedString’
| xkb/xkmread.c:152:20: warning[-Wanalyzer-tainted-offset]: use of attacker-controlled value as offset without upper-bounds checking
| 150|           str[max_len - 1] = '\0';
| 151|       else
| 152|->         str[count] = '\0';
| 153|       count = XkbPaddedSize(nRead) - nRead;
| 154|       if (count > 0)

To fix that issue, use a separate variable nStored to keep track of the
bytes actually read instead of relying on the provided count.

See-also: https://gitlab.freedesktop.org/xorg/xserver/-/work_items/1817
Signed-off-by: Olivier Fourdan <ofourdan@redhat.com>
Assisted-by: Cursor AI