glamor: Prevent potential NULL pointer dereference in glamor_composite_glyphs()
As reported by the static analyzer:

Error: GCC_ANALYZER_WARNING (CWE-476): [#def31]
| include/Xprintf.h:29: included_from: Included from here.
| glamor/glamor_composite_glyphs.c:23: included_from: Included from here.
| glamor/glamor_composite_glyphs.c: scope_hint: In function ‘glamor_composite_glyphs’
| glamor/glamor_composite_glyphs.c:449:70: warning[-Wanalyzer-null-dereference]: dereference of NULL ‘glyph_atlas’
| include/privates.h: scope_hint: In function ‘glamor_composite_glyphs’
| glamor/glamor_composite_glyphs.c: scope_hint: In function ‘glamor_composite_glyphs’
| include/privates.h: scope_hint: In function ‘glamor_composite_glyphs’
| include/privates.h: scope_hint: In function ‘glamor_composite_glyphs’
| glamor/glamor_composite_glyphs.c: scope_hint: In function ‘glamor_composite_glyphs’
| 447|                       /* Glyph not cached in current atlas?
| 448|                        */
| 449|->                     if (_X_UNLIKELY(glyph_priv->serial != glyph_atlas->serial)) {
| 450|                           if (!glamor_glyph_can_add(glyph_atlas, glyph_atlas_dim, glyph_draw)) {
| 451|                               if (glyphs_queued) {

The variable glyph_atlas can be NULL before it’s initialized, add a
safety check to avoid dereferencing a NULL pointer.

See-also: https://gitlab.freedesktop.org/xorg/xserver/-/work_items/1817
Signed-off-by: Olivier Fourdan <ofourdan@redhat.com>
Assisted-by: Cursor AI