xwayland: Secure dmabuf attribute packing in xwl_glamor_gbm_create_pixmap_for_bo()
As reported by the static analyzer:

Error: GCC_ANALYZER_WARNING (CWE-121): [#def56]
| hw/xwayland/xwayland-glamor-gbm.c:248:30: warning[-Wanalyzer-out-of-bounds]: stack-based buffer overflow
| hw/xwayland/xwayland-glamor-gbm.c:259:13: note: in expansion of macro ‘ADD_ATTR’
| include/privates.h: scope_hint: In function ‘xwl_glamor_gbm_create_pixmap_for_bo’
| hw/xwayland/xwayland-glamor-gbm.c: scope_hint: In function ‘xwl_glamor_gbm_create_pixmap_for_bo’
| include/privates.h: scope_hint: In function ‘xwl_glamor_gbm_create_pixmap_for_bo’
| hw/xwayland/xwayland-glamor-gbm.c: scope_hint: In function ‘xwl_glamor_gbm_create_pixmap_for_bo’
| hw/xwayland/xwayland-glamor-gbm.c:250:9: note: in expansion of macro ‘ADD_ATTR’
| hw/xwayland/xwayland-glamor-gbm.c:259:13: note: in expansion of macro ‘ADD_ATTR’
| hw/xwayland/xwayland-glamor-gbm.c:248:30: note: write of 4 bytes to beyond the end of ‘img_attrs’
| hw/xwayland/xwayland-glamor-gbm.c:259:13: note: in expansion of macro ‘ADD_ATTR’
| hw/xwayland/xwayland-glamor-gbm.c:248:30: note: valid subscripts for ‘img_attrs’ are ‘[0]’ to ‘[63]’
| hw/xwayland/xwayland-glamor-gbm.c:259:13: note: in expansion of macro ‘ADD_ATTR’
| 246|           do {                                                            \
| 247|               assert(((num) + 1) < (sizeof(attrs) / sizeof((attrs)[0]))); \
| 248|->             (attrs)[(num)++] = (attr);                                  \
| 249|           } while (0)
| 250|           ADD_ATTR(img_attrs, attr_num, EGL_WIDTH);

Error: GCC_ANALYZER_WARNING (CWE-121): [#def57]
| hw/xwayland/xwayland-glamor-gbm.c: scope_hint: In function ‘xwl_glamor_gbm_create_pixmap_for_bo’
| hw/xwayland/xwayland-glamor-gbm.c:258:24: warning[-Wanalyzer-out-of-bounds]: stack-based buffer overflow
| include/cursor.h:53: included_from: Included from here.
| include/scrnintstr.h:53: included_from: Included from here.
| glamor/glamor.h:32: included_from: Included from here.
| hw/xwayland/xwayland-glamor-gbm.c:53: included_from: Included from here.
| include/privates.h: scope_hint: In function ‘xwl_glamor_gbm_create_pixmap_for_bo’
| hw/xwayland/xwayland-glamor-gbm.c: scope_hint: In function ‘xwl_glamor_gbm_create_pixmap_for_bo’
| include/privates.h: scope_hint: In function ‘xwl_glamor_gbm_create_pixmap_for_bo’
| hw/xwayland/xwayland-glamor-gbm.c: scope_hint: In function ‘xwl_glamor_gbm_create_pixmap_for_bo’
| hw/xwayland/xwayland-glamor-gbm.c:250:9: note: in expansion of macro ‘ADD_ATTR’
| hw/xwayland/xwayland-glamor-gbm.c:258:24: note: write of 4 bytes to beyond the end of ‘fds’
| hw/xwayland/xwayland-glamor-gbm.c:258:24: note: valid subscripts for ‘fds’ are ‘[0]’ to ‘[3]’
| 256|
| 257|           for (plane = 0; plane < num_planes; plane++) {
| 258|->             fds[plane] = gbm_bo_get_fd_for_plane(bo, plane);
| 259|               ADD_ATTR(img_attrs, attr_num, planeAttrs[plane][PLANE_FD]);
| 260|               ADD_ATTR(img_attrs, attr_num, fds[plane]);

Error: GCC_ANALYZER_WARNING (CWE-126): [#def58]
| hw/xwayland/xwayland-glamor-gbm.c:259:60: warning[-Wanalyzer-out-of-bounds]: buffer over-read
| hw/xwayland/xwayland-glamor-gbm.c:248:33: note: in definition of macro ‘ADD_ATTR’
| include/privates.h: scope_hint: In function ‘xwl_glamor_gbm_create_pixmap_for_bo’
| hw/xwayland/xwayland-glamor-gbm.c: scope_hint: In function ‘xwl_glamor_gbm_create_pixmap_for_bo’
| include/privates.h: scope_hint: In function ‘xwl_glamor_gbm_create_pixmap_for_bo’
| hw/xwayland/xwayland-glamor-gbm.c: scope_hint: In function ‘xwl_glamor_gbm_create_pixmap_for_bo’
| hw/xwayland/xwayland-glamor-gbm.c:250:9: note: in expansion of macro ‘ADD_ATTR’
| hw/xwayland/xwayland-glamor-gbm.c:248:33: note: in definition of macro ‘ADD_ATTR’
| hw/xwayland/xwayland-glamor-gbm.c:259:60: note: read of 4 bytes from after the end of ‘planeAttrs’
| hw/xwayland/xwayland-glamor-gbm.c:248:33: note: in definition of macro ‘ADD_ATTR’
| hw/xwayland/xwayland-glamor-gbm.c:259:60: note: valid subscripts for ‘planeAttrs’ are ‘[0]’ to ‘[3]’
| hw/xwayland/xwayland-glamor-gbm.c:248:33: note: in definition of macro ‘ADD_ATTR’
| 257|           for (plane = 0; plane < num_planes; plane++) {
| 258|               fds[plane] = gbm_bo_get_fd_for_plane(bo, plane);
| 259|->             ADD_ATTR(img_attrs, attr_num, planeAttrs[plane][PLANE_FD]);
| 260|               ADD_ATTR(img_attrs, attr_num, fds[plane]);
| 261|               ADD_ATTR(img_attrs, attr_num, planeAttrs[plane][PLANE_OFFSET]);

Error: GCC_ANALYZER_WARNING (CWE-126): [#def59]
| hw/xwayland/xwayland-glamor-gbm.c:261:60: warning[-Wanalyzer-out-of-bounds]: buffer over-read
| hw/xwayland/xwayland-glamor-gbm.c:248:33: note: in definition of macro ‘ADD_ATTR’
| include/privates.h: scope_hint: In function ‘xwl_glamor_gbm_create_pixmap_for_bo’
| hw/xwayland/xwayland-glamor-gbm.c: scope_hint: In function ‘xwl_glamor_gbm_create_pixmap_for_bo’
| include/privates.h: scope_hint: In function ‘xwl_glamor_gbm_create_pixmap_for_bo’
| hw/xwayland/xwayland-glamor-gbm.c: scope_hint: In function ‘xwl_glamor_gbm_create_pixmap_for_bo’
| hw/xwayland/xwayland-glamor-gbm.c:250:9: note: in expansion of macro ‘ADD_ATTR’
| hw/xwayland/xwayland-glamor-gbm.c:248:33: note: in definition of macro ‘ADD_ATTR’
| hw/xwayland/xwayland-glamor-gbm.c:261:60: note: read of 4 bytes from after the end of ‘planeAttrs’
| hw/xwayland/xwayland-glamor-gbm.c:248:33: note: in definition of macro ‘ADD_ATTR’
| hw/xwayland/xwayland-glamor-gbm.c:261:60: note: valid subscripts for ‘planeAttrs’ are ‘[0]’ to ‘[3]’
| hw/xwayland/xwayland-glamor-gbm.c:248:33: note: in definition of macro ‘ADD_ATTR’
| 259|               ADD_ATTR(img_attrs, attr_num, planeAttrs[plane][PLANE_FD]);
| 260|               ADD_ATTR(img_attrs, attr_num, fds[plane]);
| 261|->             ADD_ATTR(img_attrs, attr_num, planeAttrs[plane][PLANE_OFFSET]);
| 262|               ADD_ATTR(img_attrs, attr_num, gbm_bo_get_offset(bo, plane));
| 263|               ADD_ATTR(img_attrs, attr_num, planeAttrs[plane][PLANE_PITCH]);

Error: GCC_ANALYZER_WARNING (CWE-126): [#def60]
| hw/xwayland/xwayland-glamor-gbm.c:263:60: warning[-Wanalyzer-out-of-bounds]: buffer over-read
| hw/xwayland/xwayland-glamor-gbm.c:248:33: note: in definition of macro ‘ADD_ATTR’
| include/privates.h: scope_hint: In function ‘xwl_glamor_gbm_create_pixmap_for_bo’
| hw/xwayland/xwayland-glamor-gbm.c: scope_hint: In function ‘xwl_glamor_gbm_create_pixmap_for_bo’
| include/privates.h: scope_hint: In function ‘xwl_glamor_gbm_create_pixmap_for_bo’
| hw/xwayland/xwayland-glamor-gbm.c: scope_hint: In function ‘xwl_glamor_gbm_create_pixmap_for_bo’
| hw/xwayland/xwayland-glamor-gbm.c:250:9: note: in expansion of macro ‘ADD_ATTR’
| hw/xwayland/xwayland-glamor-gbm.c:248:33: note: in definition of macro ‘ADD_ATTR’
| hw/xwayland/xwayland-glamor-gbm.c:263:60: note: read of 4 bytes from after the end of ‘planeAttrs’
| hw/xwayland/xwayland-glamor-gbm.c:248:33: note: in definition of macro ‘ADD_ATTR’
| hw/xwayland/xwayland-glamor-gbm.c:263:60: note: valid subscripts for ‘planeAttrs’ are ‘[0]’ to ‘[3]’
| hw/xwayland/xwayland-glamor-gbm.c:248:33: note: in definition of macro ‘ADD_ATTR’
| 261|               ADD_ATTR(img_attrs, attr_num, planeAttrs[plane][PLANE_OFFSET]);
| 262|               ADD_ATTR(img_attrs, attr_num, gbm_bo_get_offset(bo, plane));
| 263|->             ADD_ATTR(img_attrs, attr_num, planeAttrs[plane][PLANE_PITCH]);
| 264|               ADD_ATTR(img_attrs, attr_num, gbm_bo_get_stride_for_plane(bo, plane));
| 265|               ADD_ATTR(img_attrs, attr_num, planeAttrs[plane][PLANE_MODIFIER_LO]);

Error: GCC_ANALYZER_WARNING (CWE-126): [#def61]
| hw/xwayland/xwayland-glamor-gbm.c:265:60: warning[-Wanalyzer-out-of-bounds]: buffer over-read
| hw/xwayland/xwayland-glamor-gbm.c:248:33: note: in definition of macro ‘ADD_ATTR’
| include/privates.h: scope_hint: In function ‘xwl_glamor_gbm_create_pixmap_for_bo’
| hw/xwayland/xwayland-glamor-gbm.c: scope_hint: In function ‘xwl_glamor_gbm_create_pixmap_for_bo’
| include/privates.h: scope_hint: In function ‘xwl_glamor_gbm_create_pixmap_for_bo’
| hw/xwayland/xwayland-glamor-gbm.c: scope_hint: In function ‘xwl_glamor_gbm_create_pixmap_for_bo’
| hw/xwayland/xwayland-glamor-gbm.c:250:9: note: in expansion of macro ‘ADD_ATTR’
| hw/xwayland/xwayland-glamor-gbm.c:248:33: note: in definition of macro ‘ADD_ATTR’
| hw/xwayland/xwayland-glamor-gbm.c:265:60: note: read of 4 bytes from after the end of ‘planeAttrs’
| hw/xwayland/xwayland-glamor-gbm.c:248:33: note: in definition of macro ‘ADD_ATTR’
| hw/xwayland/xwayland-glamor-gbm.c:265:60: note: valid subscripts for ‘planeAttrs’ are ‘[0]’ to ‘[3]’
| hw/xwayland/xwayland-glamor-gbm.c:248:33: note: in definition of macro ‘ADD_ATTR’
| 263|               ADD_ATTR(img_attrs, attr_num, planeAttrs[plane][PLANE_PITCH]);
| 264|               ADD_ATTR(img_attrs, attr_num, gbm_bo_get_stride_for_plane(bo, plane));
| 265|->             ADD_ATTR(img_attrs, attr_num, planeAttrs[plane][PLANE_MODIFIER_LO]);
| 266|               ADD_ATTR(img_attrs, attr_num, (uint32_t)(modifier & 0xFFFFFFFFULL));
| 267|               ADD_ATTR(img_attrs, attr_num, planeAttrs[plane][PLANE_MODIFIER_HI]);

Error: GCC_ANALYZER_WARNING (CWE-126): [#def62]
| hw/xwayland/xwayland-glamor-gbm.c:267:60: warning[-Wanalyzer-out-of-bounds]: buffer over-read
| hw/xwayland/xwayland-glamor-gbm.c:248:33: note: in definition of macro ‘ADD_ATTR’
| include/privates.h: scope_hint: In function ‘xwl_glamor_gbm_create_pixmap_for_bo’
| hw/xwayland/xwayland-glamor-gbm.c: scope_hint: In function ‘xwl_glamor_gbm_create_pixmap_for_bo’
| include/privates.h: scope_hint: In function ‘xwl_glamor_gbm_create_pixmap_for_bo’
| hw/xwayland/xwayland-glamor-gbm.c: scope_hint: In function ‘xwl_glamor_gbm_create_pixmap_for_bo’
| hw/xwayland/xwayland-glamor-gbm.c:250:9: note: in expansion of macro ‘ADD_ATTR’
| hw/xwayland/xwayland-glamor-gbm.c:248:33: note: in definition of macro ‘ADD_ATTR’
| hw/xwayland/xwayland-glamor-gbm.c:267:60: note: read of 4 bytes from after the end of ‘planeAttrs’
| hw/xwayland/xwayland-glamor-gbm.c:248:33: note: in definition of macro ‘ADD_ATTR’
| hw/xwayland/xwayland-glamor-gbm.c:267:60: note: valid subscripts for ‘planeAttrs’ are ‘[0]’ to ‘[3]’
| hw/xwayland/xwayland-glamor-gbm.c:248:33: note: in definition of macro ‘ADD_ATTR’
| 265|               ADD_ATTR(img_attrs, attr_num, planeAttrs[plane][PLANE_MODIFIER_LO]);
| 266|               ADD_ATTR(img_attrs, attr_num, (uint32_t)(modifier & 0xFFFFFFFFULL));
| 267|->             ADD_ATTR(img_attrs, attr_num, planeAttrs[plane][PLANE_MODIFIER_HI]);
| 268|               ADD_ATTR(img_attrs, attr_num, (uint32_t)(modifier >> 32ULL));
| 269|           }

Those are presumably valid, also because the code relies on assert() to
check bound checking (and assert() will have no effect if built with
NDEBUG).

The proposed fix includes:

- runtime validation that num_planes is within GBM_MAX_PLANES and within
  the number of planeAttrs entries
- runtime validation that the computed attribute count fits img_attrs
- ADD_ATTR now has a runtime bounds check (bails out on overflow)
- fds[] initialization is now bounded by GBM_MAX_PLANES

See-also: https://gitlab.freedesktop.org/xorg/xserver/-/work_items/1817
Signed-off-by: Olivier Fourdan <ofourdan@redhat.com>
Assisted-by: Cursor AI